### ISSUE TITLE
Dev env setup

### ISSUE THREAD

**Issue by MattSturgeon** [firstdarkdev/modpublisher#10]
In my setup, generated property getters (e.g. `extension .getVersion()`) are missing in the IDE, but the project builds fine using `gradle build`.

It's as if whatever annotation processor should generate the methods is only being run in a "real" build, and not the IDE sync.

When I've worked with Gradle plugins in the past, this wasn't an issue...

Looking at [the userguide](https://docs.gradle.org/current/userguide/java_gradle_plugin.html), the only thing stands out is that `@getter` is used instead of `@Input`, but IDK if that'd make any real difference?

Is this an issue with your setup too? Am I missing some IDE plugin or build setup task?

If I am missing something, it'd be great to document setting up a dev env in the README or a `CONTRIBUTING.md`.

**Comment by hypherionmc** [comment]
You are correct in that the getters are missing from the actual code in the IDE.

The `@Getter` from lombok generates this automatically, that's why it's valid to use, even though it's not actually shown in the code.

Newer versions of IntelliJ have no issue supporting this. Older versions required you to install the lombok plugin.

**Comment by MattSturgeon** [comment]
> Newer versions of IntelliJ have no issue supporting this. Older versions required you to install the lombok plugin.

Interesting, I tried both 2023.3.x and 2024.4.1 RC (EAP). Neither IDE knew about the getters until installing the lombak plugin. Builds work regardless though.

If a `CONTRIBUTING.md` is added, the lombak plugin is definitely worth mentioning. :+1:

**Comment by hypherionmc** [comment]
That's interesting. It just sorta "always worked on my system". Guess I had the plugin installed already.

Will definitely add a mention of it somewhere
