### ISSUE TITLE
Snapshots not published to maven?

### ISSUE THREAD

**Issue by MattSturgeon** [firstdarkdev/modpublisher#27]
Attempting to bump my dependency to 2.1.7, but it doesn't seem to be in your maven repo.

Are snapshots being published?

I've tried
```gradle
plugins {
  id "com.hypherionmc.modutils.modpublisher-snapshot" version "2.1.7+snapshot.0" apply false
}
```
and

```gradle
plugins {
  id "com.hypherionmc.modutils.modpublisher" version "2.1.7+snapshot.0" apply false
}
```

```
Plugin Repositories (could not resolve plugin artifact 'com.hypherionmc.modutils.modpublisher-snapshot:com.hypherionmc.modutils.modpublisher-snapshot.gradle.plugin:2.1.7+snapshot.0')
  Searched in the following repositories:
    maven(https://maven.firstdark.dev/releases/)
    Gradle Central Plugin Repository
```

Looking [here](https://maven.firstdark.dev/#/releases/com/hypherionmc/modutils/modpublisher) and [here](https://maven.firstdark.dev/#/releases/com/hypherionmc/modutils/modpublisher/com.hypherionmc.modutils.modpublisher.gradle.plugin), I also can't see any snapshot builds 😖

**Comment by hypherionmc** [comment]
Yes, they are published.

Just swap the maven url from `releases` to `snapshots`. So `https://maven.firstdark.dev/snapshots`

**Comment by MattSturgeon** [comment]
Ah, thanks. Adding `"https://maven.firstdark.dev/snapshots/"` to my pluginManagement repos fixed the issue.

Looking more carefully I see that's also mentioned in the README, so I'll close this.
