### ISSUE TITLE
Feature: upload different artifacts to each platform

### ISSUE THREAD

**Issue by MattSturgeon** [firstdarkdev/modpublisher#3]
For example, [Freecam](https://github.com/hashalite/Freecam) produces a "normal" build as well as a "modrinth" build, as some options need to be restricted to comply with their ToS.

Could [`artifact`](https://github.com/firstdarkdev/modpublisher/blob/69f0b2227650c332c42ddf3e0bab752430fcb7ca/src/main/java/com/hypherionmc/modpublisher/plugin/ModPublisherGradleExtension.java#L62) be replaced with a [`NamedDomainObjectContainer`](https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectContainer.html), [`MapProperty`](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/MapProperty.html), or similar?

The existing API could be maintained by having a `setArtifact()` input that assigns the given artifact to all (recognized) entries.

**Comment by hypherionmc** [comment]
Hmm makes total sense.

What I can do is, keep setArtifact, and then add a second one that takes in a string/enum matching the platform.

So for example:

```gradle
setArtifact(jar) // Used for all Platforms
setArtifact("modrinth", jar) // Only uploaded to modrinth
setArtifact(Platform.Modrinth, jar) // Only uploaded to modrinth
```

Would something like that work?

**Comment by MattSturgeon** [comment]
That'd be perfect. (Merry christmas btw :santa: ).

How would it behave if `setArtifact(jar)` is used in tandem with `setArtifact(__, jar)`? Would the first invocation set the "default" and the second then overwrite the specified platform?

**Comment by hypherionmc** [comment]
Oh yeah, it's christmas lol. Merry christmas.

If there is no specific override for a platform, it will use the global one. If no global one, and no platform one is found, it will throw an error.

So for example:

```gradle
setArtifact(jar) // Global
setArtifact("modrinth", modrinthJar) // Modrinth task will use this artifact
```

Then GitHub/Curseforge will use global, and modrinth will use the modrinth jar

**Comment by hypherionmc** [comment]
Implemented with `2.0.2`

Configuration:

```gradle
setArtifact(jar) // Global Artifact
setPlatformArtifact("modrinth", modrinthJar) // Override for Modrinth.
setPlatformArtifact("curseforge", curseJar) // Override for Curse
setPlatformArtifact(Platform.GitHub, githubJar) // Override GitHub jar
```

or Kotlin

```kotlin
artifact.set(tasks.jar) // Global Artifact
setPlatformArtifact("modrinth", tasks.modrinthJar) // Override for Modrinth.
setPlatformArtifact("curseforge", tasks.curseJar) // Override for Curse
setPlatformArtifact(Platform.GitHub, tasks.githubJar) // Override GitHub jar
```

If setPlatformArtifact is not called for a platform, artifact will be used. If neither is set, an error will be thrown

**Comment by MattSturgeon** [comment]
Wonderful, thank you!

**Comment by hypherionmc** [comment]
You're welcome. Do let me know if you have any questions or need anything else :)
