### ISSUE TITLE
Feature: Define supported Java versions for CurseForge uploads

### ISSUE THREAD

**Issue by iChun** [firstdarkdev/modpublisher#4]
As per title:

CurseForge allows marking supported Java versions in mod files but there lacks an ability to tag uploaded files with that information. Hoping to have a method added for that.

Thanks!

**Comment by hypherionmc** [comment]
Hey there

In theory it should be possible to just add the java versions as a game version (Like Java 8, Java 17) as curse just handles them as game versions.

The only place I see this being a problem is with Modrinth. 


So I can either add a separate method to add java versions, which will only apply it to curse, or, I need to filter out any version that starts with Java on Modrinth.


Maybe having a dedicated method for this should be fine. I've been wanting to implement some auto detection features like Cursegradle and Minotaur has. Just haven't bothered yet cause no one asked for it lol

**Comment by hypherionmc** [comment]
Implemented with 2.0.3.

```groovy
// Add supported java versions. Currently only used by CurseForge
setJavaVersions("Java 8", "Java 11")
```

**Comment by MattSturgeon** [comment]
It'd be great if `setJavaVersion` could also accept [`org.gradle.api.JavaVersion`](https://docs.gradle.org/current/javadoc/org/gradle/api/JavaVersion.html)s.

That way we can reference `project.java.targetCompatibility` or `project.java.toolchain.languageVersion`.

`JavaVersion` can be converted to the current string format using `"Java ${it.getMajorVersion()}"`.

**Comment by hypherionmc** [comment]
Damn discord webhooks being faster than my email lol.

Great idea. Will look at adding support for it
