### ISSUE TITLE
bug: mod slugs don't work in modrinthDepends

### ISSUE THREAD

**Issue by MattSturgeon** [firstdarkdev/modpublisher#6]
Note: I originally wrote this as a feature request, before noticing that the documentation indicates this should be supported. Therefore some of my phrasing may be off for a bug report:

Currently `modrinthDepends` requires mod ID values, while `curseDepends` can use slugs.

This would enable the following concise configuration in cases where mod slugs are identical on both platforms:

```gradle
[ modrinthDepends, curseDepends ].each {
    it.required "fabric-api"
    it.optional "modmenu"
}
```

The following error bubbles up from Modrinth's API when using a slug that includes hyphens: _([stack trace](https://pastebin.com/raw/YfLEB7ui))_

```
EndpointException(error=invalid_input, description=Error while parsing JSON: Invalid character '-' in base62 encoding at line 1 column 130)
```

The issue seems to come from [this line](https://github.com/firstdarkdev/modpublisher/blob/546f5171413bfa6260912085b5d553fc8d40e04b/src/main/java/com/hypherionmc/modpublisher/tasks/ModrinthPublishTask.java#L124) assuming it can use the configured value as the mod id, without first attempting to resolve the id from a slug. A test should probably be added for modrinth dependencies configured using slugs.

I believe the only way to implement this is by using the modrinth API: e.g. [`https://api.modrinth.com/v2/project/fabric-api`](https://api.modrinth.com/v2/project/fabric-api) returns a JSON object with the `"id"` property set to `"P7dR8mSH"` (assuming you get a `200` response of course).

- Since API requests are required, it's probably a good idea to document that ids are preferred.
- As a stretch goal, it might be nice to cache the resolved IDs somehow (IDK how easy this is to do with Gradle's cache?)
- If you'd rather not implement this, perhaps document more explicitly why `modrinthDepends` needs id values?

**Comment by hypherionmc** [comment]
Hey

Thanks for the report. This is interesting actually, cause I'm pretty sure we have users using slugs as well [as seen here](https://github.com/GenerationsMod/Generations-Core/blob/52bf4bda92d4f924f87147cf2f414d0d680c2ad8/fabric/build.gradle.kts#L124) and [here](https://github.com/GenerationsMod/Generations-Structures/blob/42426034c51bc297155cb03ac5842b1d7f9f04fa/fabric/build.gradle.kts#L109)

Unless this is an edge case where mixing an ID and a slug causes an issue, OR, a recent modrinth change/bug.

**Comment by MattSturgeon** [comment]
> This is interesting actually, cause I'm pretty sure we have users using slugs as well [as seen here](https://github.com/GenerationsMod/Generations-Core/blob/52bf4bda92d4f924f87147cf2f414d0d680c2ad8/fabric/build.gradle.kts#L124) and [here](https://github.com/GenerationsMod/Generations-Structures/blob/42426034c51bc297155cb03ac5842b1d7f9f04fa/fabric/build.gradle.kts#L109)

That _is_ interesting. If those cases work then ours should've done too...

Tagging @hashalite as he was the one who actually ran into the issue.

> Unless this is an edge case where mixing an ID and a slug causes an issue

We were exclusively using slugs when hitting this issue.

The only thing I can think of that could trigger an edge case is that we set some dependencies in all projects, via a `subprojects` block in the root script, and others exclusively in the `:fabric` project...

The other difference is I used `[ modrinthDepends, curseDepends ].each` rather than something like:

```gradle
[ "fabric-api" ].each {
    curseDepends.required it
    modrinthDepends.required it
}
```

> OR, a recent modrinth change/bug

Unified-publishing has had [code handling the case](https://github.com/shedaniel/unified-publishing/blob/9bd9e85f21c30a3200501ab47e40e6cea74985f1/src/main/java/me/shedaniel/unifiedpublishing/ModrinthPublishingTarget.java#L97-L113) (LGPL) since their initial commit 2 years ago.

Do you have code I've missed converting from slug to id or are you relying on some modrinth feature?

> A test should probably be added for modrinth dependencies configured using slugs.

Do you already have tests covering id/slug usage?

**Comment by hypherionmc** [comment]
There isn't an added test case for this, but both minotaur (Modrinth's official gradle plugin) and modpublisher use Modrinth4j as the "backend" library. Individual upload tests were also done to modrinth, to confirm if this works or not (on their staging platform).

So in theory, anything minotaur allows, should work with modpublisher as well.

I am checking in with Modrinth as well to confirm if there was a recent api change, or if this is indeed just a bug. 


Alternatively, the chance is always there that this is a bug introduced with the addition of the last feature requests, so definitely some testing to be done here.


Just as reference, this is from the minotaur GitHub page, where they indicate using slugs, instead of ID's

```groovy
dependencies { // A special DSL for creating dependencies
        // scope.type
        // The scope can be `required`, `optional`, `incompatible`, or `embedded`
        // The type can either be `project` or `version`
        required.project "fabric-api" // Creates a new required dependency on Fabric API
        optional.version "sodium", "mc1.19.3-0.4.8" // Creates a new optional dependency on this specific version of Sodium
    }
    ```

**Comment by hypherionmc** [comment]
So with further investigation, minotaur does indeed convert slugs into ID's before upload. I just missed that completely.

The same conversion is now implemented starting with 2.0.4.

This now also allows you to use a slug as the projectid, instead of just requiring an id.

Thanks for reporting this. Not sure how this was working before, but strange things happen I guess

**Comment by MattSturgeon** [comment]
Great thanks. I'll re-open if we encounter any issues testing this.

> This now also allows you to use a slug as the projectid, instead of just requiring an id.

Is this true for the curseforge project id too? I could only see modrinth-related changes in the latest commits.

**Comment by MattSturgeon** [comment]
Mod slugs without hyphens (e.g. `"modmenu"`) get a false positive for `isModrinthID`.

I'm not sure if a regex will able to properly differentiate between IDs and slugs. You could try parsing as base64 (assuming that's what the IDs are using), but I think even that could have some false positives.

Looks like unified-publishing [always](https://github.com/shedaniel/unified-publishing/blob/9bd9e85f21c30a3200501ab47e40e6cea74985f1/src/main/java/me/shedaniel/unifiedpublishing/ModrinthPublishingTarget.java#L97-L113) does the API request, without attempting to detect if it already has an id. So I assume the `project` API can accept _either_ a slug or an id and return the same object.

I think minotaur is [doing](https://github.com/modrinth/minotaur/blob/a151c425fb128cd5384242f25b6fbb0a1d18e325/src/main/java/com/modrinth/minotaur/dependencies/Dependency.java#L62) the same, or possibly they know they always have slugs not IDs?

**Comment by hypherionmc** [comment]
For regex sakes.... 

I was hoping to save on API calls, if it's already an ID, but guess the best solution is to always make the request and build up some cache later on.

> Is this true for the curseforge project id too? I could only see modrinth-related changes in the latest commits.

As far as I am aware, curseforge does not support project slugs at all via the api. Will confirm this as well.

Only problem with CurseForge is that all the API endpoints require an API KEY, which would mean I need to apply for another API key and ship it in code 😓 .


I'll push out a fix for the modrinth issue later today

**Comment by MattSturgeon** [comment]
> For regex sakes....
>
> I was hoping to save on API calls, if it's already an ID

Agreed that would've been ideal. At least IDs can be safely cached since they should literally never change.

> As far as I am aware, curseforge does not support project slugs at all via the api. Will confirm this as well.

Being able to use slugs as project IDs isn't important for me; it's clear from the context what project the ID relates to.

IMO it's better to avoid the API calls for project IDs.

> Only problem with CurseForge is that all the API endpoints require an API KEY,

Ran into that myself; wasn't able to run `publishCurseforge` with an invalid key even if `debug=true`.

> I'll push out a fix for the modrinth issue later today

Great thanks 🎉😄

**Comment by hypherionmc** [comment]
> Ran into that myself; wasn't able to run publishCurseforge with an invalid key even if debug=true

Was thinking for a moment this was a bug, but then I remembered even with debugging, it still makes a request to CurseForge to retrieve the game/loader/java id's for use in the upload, so it would fail with an invalid api key.

I've been planning a mockup of the CurseForge upload API that can be used for debugging purposes, so it's possible to do a full upload run, without ever uploading anything to CurseForge.

On modrinth, you can use the Staging API to test such things, but sadly Curse doesn't have a similar system.

**Comment by hypherionmc** [comment]
Removed the ID check in 2.0.5. 

Will add a cache system later on. Have some other changes I want to do as well, so want to do them as one big update (like deprecating version and replacing it with modVersion, so it doesn't interfere with gradle's version parameter)
